language: php

php:
  - 7.2

sudo: false
dist: trusty

node_js:
  - '8'

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.drupal/db

before_install:
  - node --version
  - npm --version

install:
  - npm install -g gulp-cli yarn
  - composer install

script:
  - vendor/bin/phpcs -p --standard=phpcs.xml.dist ignore_errors_on_exit 0 --runtime-set ignore_warnings_on_exit 0
  - cd "$TRAVIS_BUILD_DIR/source" && gulp validate
