language: php

php:
  - 7.2

sudo: false
dist: trusty

node_js:
  - '10'

install:
  - npm install -g gulp-cli yarn
  - composer install

script:
  - cd "$TRAVIS_BUILD_DIR/source" && gulp validate
  - cd "$TRAVIS_BUILD_DIR" && vendor/bin/phpcs -p --colors
