sudo: false
os:
  - linux
language: node_js
node_js:
  - "10"
cache: yarn
matrix:
  fast_finish: true
before_install:
  - node --version
  - npm --version
install:
  - cd source
  - npm install -g gulp-cli yarn
  - yarn
script:
  - gulp validate
