language: php

php:
  - 7.2

sudo: false
dist: trusty

node_js:
  - '8'

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.drupal/db

before_install:
  - node --version
  - npm --version

install:
  - npm install -g gulp-cli yarn
  - composer install

script:
  - cd source && gulp validate && cd ..
  - vendor/bin/phpcs --standard=phpcs.xml.dist -p --colors
